theme: jekyll-theme-architect
title: Guide for DOTE users
description: DOTE (Distributed Open Transcription Environment)
URL: "https://bigsoftvideo.github.io/DOTE"
image: "/images/logo.png"
markdown: GFM
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - contributing.md
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"